---
# tasks file for php
  - name: Install fpm-
    yum: name={{ item }} state=present
    with_items:
        - php70
        - php70-devel
        - php70-gd
        - php70-fpm
        - php70-mbstring
        - php70-pdo
        - php70-mcrypt
        - php70-mysqlnd
        - php70-pgsql
        - php70-opcache
        - php70-xml
        - php70-zip
        - php70-pecl-apcu
        - php70-pecl-apcu-devel

#php setting
# we should edit some parameter for eccube
  - lineinfile: dest=/etc/php.ini
          regexp=';date.timezone ='
          line='date.timezone = Asia/Tokyo'
  - lineinfile: dest=/etc/php.ini
          regexp='session.gc_maxlifetime ='
          line='session.gc_maxlifetime = 1800'
  - lineinfile: dest=/etc/php.ini
          regexp='memory_limit ='
          line='memory_limit = 256M'

  #php-fpm setting
  - name: change listen
    command: sed -i "s|listen = 127.0.0.1:9000|listen = /var/run/php7-fpm.sock|g" /etc/php-fpm.d/www.conf

  - name: change listen2
    command: sed -i "s|server 127.0.0.1:9000|server unix:/var/run/php7-fpm.sock|g" /etc/nginx/conf.d/php-fpm.conf-7.0

  - name: change user
    command: sed -i "s|user = apache|user = nginx|g" /etc/php-fpm.d/www.conf

  - name: change group
    command: sed -i "s|group = apache|group = nginx|g" /etc/php-fpm.d/www.conf

  - name: uncomment listen.owner
    command: sed -i "s|;listen.owner = nobody|listen.owner = nginx|g" /etc/php-fpm.d/www.conf

  - name: uncomment listen.group
    command: sed -i "s|;listen.group = nobody|listen.group = nginx|g" /etc/php-fpm.d/www.conf

  - name: uncomment listen.owner
    command: sed -i "s|;listen.mode = 0660|listen.mode = 0660|g" /etc/php-fpm.d/www.conf

  - name: Automatic load when boot
    command: chkconfig php-fpm on

  - name: change session dir
    command: chown -R nginx:nginx /var/lib/php/7.0/session/
